[package]
name = "mirakc-timeshift-fs"
version = "1.0.20"
authors = ["Contributors of mirakc"]
description = "A userspace filesystem to expose timeshift records as files"
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
clap = "2.34.0"
fuser = "0.9.1"
indexmap = { version = "1.7.0", features = ["serde-1"] }
libc = "0.2.110"
log = "0.4.14"
mirakc-core = { path = "../mirakc-core" }
serde_json = { version = "1.0.72", features = ["preserve_order"] }
sanitize-filename = "0.3.0"

[dev-dependencies]
assert_matches = "1.5.0"
