[package]
name = "mirakc-timeshift-fs"
version = "0.18.0"
authors = ["Contributors of mirakc"]
description = "A userspace filesystem to expose timeshift records as files"
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
clap = "2.33.3"
fs2 = "0.4.3"
fuser = "0.8.0"
indexmap = { version = "1.6.2", features = ["serde-1"] }
libc = "0.2.97"
log = "0.4.14"
mirakc-core = { path = "../mirakc-core" }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
sanitize-filename = "0.3.0"

[dev-dependencies]
assert_matches = "1.5.0"
