version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: actix
  - package-ecosystem: npm
    directory: /scripts/perf-metrics
    schedule:
      interval: daily
