version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: '01:01'  # UTC
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '07:07'  # UTC
