version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: '03:03'
      timezone: "Asia/Tokyo"
  - package-ecosystem: npm
    directory: /scripts/perf-metrics
    schedule:
      interval: daily
      time: '05:05'
      timezone: "Asia/Tokyo"
