[package]
name = "mirakc"
version = "0.1.0"
authors = ["Masayuki Nagamachi <masnagam@gmail.com>"]
description = "A Mirakurun clone written in Rust"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
actix = "0.8"
actix-web = "1.0"
bytes = "0.4"
cfg-if = "0.1"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33"
failure = "0.1"
futures = "0.1"
humantime = "1.3"
indexmap = { version = "1.0", features = ["serde-1"] }
log = "0.4"
mustache = "0.9"
num_cpus = "1.10"
pretty_env_logger = "0.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_yaml = "0.8"
shell-words = "0.1"
tokio = "0.1"

[dev-dependencies]
matches = "0.1"
