name: CI

on:
  push:
    branches:
      - main
      - release
      - trial-*
    paths-ignore:
      - '**.md'

jobs:
  build:
  cross-build:
  coverage:
    needs:
      - build
      - cross-build
