name: Daily (main)

on:
  schedule:
    - cron: '13 13 * * *'  # UTC

env:
  MIRAKC_GA_REF_NAME: main
  MIRAKC_GA_REF_TYPE: branch
  # Use PAT in order to invoke other workflows.
  MIRAKC_GA_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

jobs:
  update:
  docker:
    if: needs.update.outputs.num-commits > 0
    needs:
      - update
