name: Daily (release)

on:
  schedule:
    - cron: '16 16 * * *'  # UTC

env:
  MIRAKC_GA_REF_NAME: release
  MIRAKC_GA_REF_TYPE: branch
  # Use PAT in order to invoke other workflows.
  MIRAKC_GA_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

jobs:
  update:
