name: Pull Request

on:
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'

jobs:
  build:
  cross-build:
  coverage:
    needs:
      - build
      - cross-build
