name: Release

on:
  push:
    tags:
      - '*'

env:
  MIRAKC_GA_REF_NAME: ${{ github.ref_name }}  # tag name
  MIRAKC_GA_REF_TYPE: ${{ github.ref_type }}  # tag
  MIRAKC_GA_TOKEN: ${{ github.token }}

jobs:
  docker:
