[package]
name = "mirakc"
version = "2.0.0-dev.0"
authors = ["Contributors of mirakc"]
description = "A Mirakurun-compatible PVR backend written in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actlet = { path = "../actlet" }
clap = { version = "4.0.32", features = ["derive", "env"] }
mirakc-core = { path = "../mirakc-core" }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
tokio = { version = "1.24.1", features = ["full"] }
tracing = "0.1.37"
