[package]
name = "mirakc"
version = "1.1.0-dev.0"
authors = ["Contributors of mirakc"]
description = "A Mirakurun-compatible PVR backend written in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actlet = { path = "../actlet" }
mirakc-core = { path = "../mirakc-core" }
serde_json = { version = "1.0.87", features = ["preserve_order"] }
structopt = "0.3.26"
tokio = { version = "1.22.0", features = ["full"] }
tracing = "0.1.37"
