[package]
name = "mirakc-core"
version = "1.1.0-dev.0"
authors = ["Contributors of mirakc"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
actix = "0.13.0"
anyhow = "1.0.65"
atty = "0.2.14"
axum = { git = "https://github.com/tokio-rs/axum", tag = "axum-v0.6.0-rc.2", features = ["headers"] }
bytes = "1.2.1"
chrono = { version = "0.4.22", features = ["serde"] }
cron = "0.12.0"
fs2 = "0.4.3"
futures = "0.3.25"
http-body = "0.4.5"
humantime = "2.1.0"
hyper = { version = "0.14.20", features = ["full"] }
indexmap = { version = "1.9.1", features = ["serde-1"] }
itertools = "0.10.5"
libc = "0.2.135"
maplit = "1.0.2"
mustache = "0.9.0"
num_cpus = "1.13.1"
once_cell = "1.15.0"
serde = { version = "1.0.145", features = ["derive", "rc"] }
serde_json = { version = "1.0.86", features = ["preserve_order"] }
serde_yaml = "0.9.13"
serde_qs = "0.10.1"
shell-words = "1.1.0"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["io-util"] }
tokio-util = { version = "0.7.4", features = ["io"] }
tower = { version = "0.4.13", default-features = false, features = ["util", "make"] }
tower-http = { version = "0.3.4", features = ["fs", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }

[dev-dependencies]
assert_matches = "1.5.0"
axum-test-helper = { path = "../axum-test-helper" }
