epg:
  cache-dir: /var/lib/mirakc/epg

server:
  # Use '0.0.0.0' (ipv4) or '::' (ipv6) if connecting from other hosts
  addrs:
    http: '0.0.0.0:40772'

channels:
  - name: MX
    type: GR
    channel: '20'
  - name: CX
    type: GR
    channel: '21'
  - name: TBS
    type: GR
    channel: '22'
  - name: TX
    type: GR
    channel: '23'
  - name: EX
    type: GR
    channel: '24'
  - name: NTV
    type: GR
    channel: '25'
  - name: ETV
    type: GR
    channel: '26'
  - name: NHK
    type: GR
    channel: '27'
  - name: BS1
    type: BS
    channel: BS15_0
  - name: BSP
    type: BS
    channel: BS03_1
  - name: BS-NTV
    type: BS
    channel: BS13_0
  - name: BS-EX
    type: BS
    channel: BS01_0
  - name: BS-TBS
    type: BS
    channel: BS01_1
  - name: BS-TX
    type: BS
    channel: BS01_2
  - name: BS-CX
    type: BS
    channel: BS13_1
  - name: BS11
    type: BS
    channel: BS09_0
  - name: BS12
    type: BS
    channel: BS09_2
  - name: OUJ
    type: BS
    channel: BS11_2

tuners:
  - name: bs1
    types: [BS]
    command: >-
      recpt1 --device /dev/px4video0 {{{channel}}} - -
  # Use a tuner on a remote host connected with SSH.
  # You need to mount a SSH private key onto a Docker container.
  - name: remote-dvb
    types: [GR]
    command: >-
      ssh <REMOTE-HOST> recdvb {{{channel}}} - -
  # Use a Mirakurun-compatible server as a tuner.
  # The duration query parameter works only for mirakc servers.
  - name: upstream
    types: [GR, BS]
    command: >-
      curl -sG <BASE-URL>/api/channels/{{{channel_type}}}/{{{channel}}}/stream

filters:
  # Optionally, you can specify a command to process TS packets before sending
  # them to a client.
  #
  # The following command processes TS packets on a remote server.
  decode-filter:
    command: >-
      socat - tcp-connect:<REMOTE-HOST>:<REMOTE-PORT>
