[package]
name = "actlet"
version = "0.1.0"
authors = ["Contributors of mirakc"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[features]
default = ["derive"]
derive = ["actlet-derive"]

[dependencies]
actlet-derive = { path = "../actlet-derive", optional = true }
async-trait = "0.1.60"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["full"] }
tokio-util = "0.7.4"
tracing = "0.1.37"
