name: CI

on:
  push:
    branches:
      - master
      - trial-*

jobs:
  build:
  cross-build:
  coverage:
    needs:
      - build
      - cross-build
  docker:
    needs:
      - build
      - cross-build
