name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
  cross-build:
  coverage:
    needs:
      - build
      - cross-build
  docker:
    needs:
      - build
      - cross-build
    strategy:
      matrix:
        include:
          - target: alpine
            tag-latest: false
            tag-semver: ''
            tag-custom: master-alpine
            tag-custom-only: true
          - target: debian  # main target
            tag-latest: false
            tag-semver: ''
            tag-custom: master-debian,master
            tag-custom-only: true
