name: CI

on:
  push:
    branches:
      - master

jobs:
  linux-build:
  macos-build:
  arm-linux-build:
  coverage:
    needs:
      - linux-build
      - macos-build
      - arm-linux-build
  docker-build-images:
    needs:
      - linux-build
      - macos-build
      - arm-linux-build
    strategy:
      matrix:
        include:
          - platform: alpine
            tag-latest: false
            tag-semver: ''
            tag-custom: master-alpine
            tag-custom-only: true
          - platform: debian
            tag-latest: false
            tag-semver: ''
            tag-custom: master-debian,master
            tag-custom-only: true
