name: CI

on:
  push:
    branches:
      - master

jobs:
  linux-build:
  macos-build:
  arm-linux-build:
  coverage:
    needs:
      - linux-build
      - macos-build
      - arm-linux-build
  docker-build-images:
    needs:
      - linux-build
      - macos-build
      - arm-linux-build
    strategy:
      matrix:
        include:
          - platform: alpine
            latest-tags: '{{version}}-alpine'
          - platform: debian
            latest-tags: '{{version}}-debian,{{version}}'
