jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2
      - name: Generate coverage data
        run: |
          cargo install cargo-tarpaulin
          cargo build
          cargo tarpaulin --out Lcov
      - name: Upload coverage data to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./lcov.info
