env:
  DOCKERHUB_IMAGE: mirakc/mirakc
  MIRAKURUN_VERSION: '3.5.0'

jobs:
  docker:
    strategy:
      matrix:
        target:
          - alpine
          - debian
        include:
          - target: alpine
            platforms: >-
              linux/amd64,
              linux/arm/v6,
              linux/arm/v7,
              linux/arm64/v8,
          - target: debian
            # docker/setup-*-action has not supported linux/arm/v5.
            platforms: >-
              linux/amd64,
              linux/arm/v7,
              linux/arm64/v8,
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker tags
        id: docker-tags
        run: |
          IMAGE="${{ env.DOCKERHUB_IMAGE }}"
          VERSION="$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)"
          TAGS="$IMAGE:${VERSION}-${{ matrix.target }}"
          if [ "${{ matrix.target }}" = "debian" ]; then
            TAGS="$TAGS,$IMAGE:${VERSION}"
          fi
          if [ "$VERSION" != "master" ]; then
            # Always update latest image tags.
            TAGS="$TAGS,$IMAGE:${{ matrix.target }}"
            if [ "${{ matrix.target }}" = "debian" ]; then
              TAGS="$TAGS,$IMAGE:latest"
            fi
          fi
          echo "Version: $VERSION"
          echo "Tags: $TAGS"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=tags::$TAGS"
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock', 'docker/build-scripts/*') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.target }}-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Make mirakurun.openapi.json
        # Wait 10 seconds for safety.
        run: |
          ./scripts/mirakurun-openapi-json -w 10 $MIRAKURUN_VERSION | ./scripts/fixup-openapi-json >mirakurun.openapi.json
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.${{ matrix.target }}
          platforms: ${{ matrix.platforms }}
          tags: ${{ steps.docker-tags.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
      - name: Test
        run: |
          # Enable experimental CLI features in Docker daemon.
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart

          IMAGE="${{ env.DOCKERHUB_IMAGE }}:${{ steps.docker-tags.outputs.version }}-${{ matrix.target }}"
          for platform in $(echo ${{ matrix.platforms }} | tr ',' ' ')
          do
            echo "Testing $IMAGE for $platform..."
            docker run --rm --platform=$platform $IMAGE --version
            docker run --rm --platform=$platform --entrypoint=recdvb $IMAGE --version
            docker run --rm --platform=$platform --entrypoint=recpt1 $IMAGE --version
            docker run --rm --platform=$platform --entrypoint=mirakc-arib $IMAGE --version
          done
