env:
  IMAGE: mirakc/mirakc
  MIRAKURUN_VERSION: '3.4.0'

jobs:
  docker:
    # Don't run on a fork.
    if: github.repository == 'mirakc/mirakc'
    strategy:
      matrix:
        target:
          - alpine
          - debian
        include:
          # tag-* values are defined in *.workflow.yml
          - target: alpine
            platforms: 'linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8'
          - target: debian
            # docker/setup-*-action has not supported linux/arm/v5
            platforms: 'linux/amd64,linux/arm/v7,linux/arm64/v8'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker metadata
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.IMAGE }}
          tag-latest: ${{ matrix.tag-latest }}
          tag-semver: ${{ matrix.tag-semver }}
          tag-custom: ${{ matrix.tag-custom }}
          tag-custom-only: ${{ matrix.tag-custom-only }}
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock', 'docker/build-scripts/*') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.target }}-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Make mirakurun.openapi.json
        # Wait 10 seconds for safety.
        run: |
          ./scripts/mirakurun-openapi-json -w 10 $MIRAKURUN_VERSION | ./scripts/fixup-openapi-json >mirakurun.openapi.json
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.${{ matrix.target }}
          platforms: ${{ matrix.platforms }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
      - name: Test
        run: |
          # Enable experimental CLI features in Docker daemon
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart

          for platform in $(echo ${{ matrix.platforms }} | tr ',' ' ')
          do
            echo "Testing $IMAGE:${{ steps.docker_meta.outputs.version }} for $platform..."
            docker run --rm --platform=$platform $IMAGE:${{ steps.docker_meta.outputs.version }} --version
            docker run --rm --platform=$platform --entrypoint=recdvb $IMAGE:${{ steps.docker_meta.outputs.version }} --version
            docker run --rm --platform=$platform --entrypoint=recpt1 $IMAGE:${{ steps.docker_meta.outputs.version }} --version
            docker run --rm --platform=$platform --entrypoint=mirakc-arib $IMAGE:${{ steps.docker_meta.outputs.version }} --version
          done
