name: Pull Request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
  cross-build:
  coverage:
    needs:
      - build
      - cross-build
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    needs:
      - build
      - cross-build
