name: Release

on:
  push:
    tags:
      - '*'

jobs:
  docker-build-images:
    strategy:
      matrix:
        include:
          - platform: alpine
            tag-latest: false
            tag-semver: |
              {{version}}-alpine
            tag-custom: alpine
            tag-custom-only: false
          - platform: debian
            tag-latest: true
            tag-semver: |
              {{version}}-debian
              {{version}}
            tag-custom: debian
            tag-custom-only: false
