name: ARM-Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        target:
          - arm-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Install cross
        run: cargo install cross
      - uses: actions/checkout@v2
      - name: Build
        run: cross build -v --release --target=${{ matrix.target }}
      - name: Run tests
        run: cross test -v --release --target=${{ matrix.target }}
