name: build

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
        rust:
          - stable
          #- nightly
    runs-on: ${{ matrix.runner }}
    continue-on-error: ${{ matrix.runner == 'macos-latest' }}  # macOS is unsupported officially
    steps:
      - uses: actions/checkout@v3
      - name: Install macfuse (macos)
        if: matrix.runner == 'macos-latest'
        run: |
          brew install macfuse pkg-config
      - name: Cache for Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.rust }}-
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: |
          cargo build -v --release
      - name: Run tests
        run: |
          cargo test -v --release
