name: coverage

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Install grcov
        uses: taiki-e/install-action@grcov
      - name: Clean
        run: |
          cargo clean
      - name: Run coverage tests
        run: |
          # Compiling actlet-derive fails due to the following error:
          #
          #   error: the linked panic runtime `panic_unwind` is not compiled
          #     with this crate's panic strategy `abort`
          #
          # So, we excludes it from the coverage.
          cargo nextest run --all-features --no-fail-fast --lib --workspace --exclude=actlet-derive
        env:
          # See https://github.com/mozilla/grcov#usage
          RUSTC_BOOTSTRAP: 1
          # See https://github.com/mozilla/grcov#example-how-to-generate-gcda-files-for-a-rust-project
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: >-
            -Zprofile
            -Ccodegen-units=1
            -Cinline-threshold=0
            -Clink-dead-code
            -Coverflow-checks=off
            -Cpanic=abort
            -Zpanic_abort_tests
          RUSTDOCFLAGS: >-
            -Cpanic=abort
      - name: Generate coverage data
        run: >-
          grcov target/debug --branch --llvm --ignore-not-existing -s .
          --ignore '*/src/main.rs' --ignore 'mirakc-core/src/error.rs'
          --ignore 'mirakc-core/src/tracing_ext.rs'
          --excl-line '<coverage:exclude/>|unimplemented!|unreachable!'
          --excl-start '<coverage:exclude>'
          --excl-stop '</coverage:exclude>'
          --excl-br-start '<coverage:exclude>'
          --excl-br-stop '</coverage:exclude>'
          -t lcov -o lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
