name: cross-build

on:
  workflow_call:

jobs:
  cross-build:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        rust:
          - stable
          #- nightly
        target:
          - i686-unknown-linux-gnu
          - arm-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache for Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-${{ matrix.rust }}-
      - name: Install cargo-binstall
        run: |
          BINSTALL_URL=https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
          curl -fsSL $BINSTALL_URL | tar -xz -C ~/.cargo/bin --no-same-owner
      - name: Install cross
        run: |
          cargo binstall --no-confirm cross
      - name: Build
        run: |
          cross build -v --release --target=${{ matrix.target }}
      - name: Run tests
        run: |
          cross test -v --release --target=${{ matrix.target }}
