name: Daily

on:
  schedule:
    - cron: '19 19 * * *'  # 19:19 (UTC)

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: >-
            This issue is stale because it has been open 30 days with no activity.
            Remove stale label or comment or this will be closed in 7 days.
          close-issue-message: >-
            This issue was closed because it has been stalled for 7 days with no activity.
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'stale'
          exempt-issue-labels: 'bug,enhancement,good first issue,help wanted'
          days-before-pr-stale: -1  # no PR will be marked as 'stale'
  update-devcontainer-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y moreutils  # sponge
          ./scripts/update-devcontainer-dockerfile
          if ! git diff --quiet -- .devcontainer/Dockerfile
          then
            # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .devcontainer/Dockerfile
            git commit -m 'build: update .devcontainer/Dockerfile'
            git push
          fi
