name: daily-on-main

on:
  schedule:
    - cron: '13 13 * * *' # UTC

jobs:
  update:
    uses: mirakc/mirakc/.github/workflows/update.yml@main
    with:
      ref-name: main
    secrets: inherit
  docker:
    if: needs.update.outputs.num-commits > 0
    needs:
      - update
    uses: mirakc/mirakc/.github/workflows/docker.yml@main
    with:
      ref-name: main
      ref-type: branch
    secrets: inherit
