name: daily-on-release

on:
  schedule:
    - cron: '16 16 * * *' # UTC

jobs:
  update:
    uses: mirakc/mirakc/.github/workflows/update.yml@main
    with:
      ref-name: release
    secrets: inherit
