name: Daily

on:
  schedule:
    - cron: '16 16 * * *'  # 16:16 (UTC)

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: >-
            This issue is stale because it has been open 30 days with no activity.
            Remove stale label or comment or this will be closed in 7 days.
          close-issue-message: >-
            This issue was closed because it has been stalled for 7 days with no activity.
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'stale'
          exempt-issue-labels: 'bug,enhancement,good first issue,help wanted'
          days-before-pr-stale: -1  # no PR will be marked as 'stale'
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Use PAT in order to invoke other workflows.
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - name: git config
        run: |
          # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Login to Docker Hub  # for avoiding the download rate limit
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Update .devcontainer/Dockerfile
        run: |
          ./scripts/update-devcontainer-dockerfile
      - name: Update resources/mirakurun.openapi.json
        run: |
          timeout 120 ./scripts/update-mirakurun-openapi-json
      - name: Update mirakc-arib
        run: |
          ./scripts/update-mirakc-arib
      - name: Push if changed
        run: |
          if git diff --quiet origin/main..HEAD
          then
            echo "No commit to push"
          else
            git push
          fi
