name: docker

on:
  workflow_call:
    inputs:
      ref-name:
        required: true
        type: string
      ref-type:
        required: true
        type: string

env:
  MAIN_DISTRO: debian

jobs:
  docker:
    strategy:
      matrix:
        distro:
          - alpine
          - debian
        include:
          - distro: alpine
            platforms: >-
              linux/386,
              linux/amd64,
              linux/arm/v6,
              linux/arm/v7,
              linux/arm64/v8,
          - distro: debian
            # docker/setup-*-action has not supported linux/arm/v5.
            platforms: >-
              linux/386,
              linux/amd64,
              linux/arm/v7,
              linux/arm64/v8,
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref-name }}
      - name: Docker tags
        id: docker-tags
        run: |
          IMAGE="{0}"  # placeholder
          VERSION="${{ inputs.ref-name }}"
          MAIN_TAG="$IMAGE:$VERSION-${{ matrix.distro }}"
          TAGS="$MAIN_TAG"
          if [ "$MAIN_DISTRO" = "${{ matrix.distro }}" ]
          then
            TAGS="$TAGS,$IMAGE:$VERSION"
          fi
          if [ "${{ inputs.ref-type }}" = tag ]
          then
            # Always update latest image tags when a new git tag is created.
            TAGS="$TAGS,$IMAGE:${{ matrix.distro }}"
            if [ "$MAIN_DISTRO" = "${{ matrix.distro }}" ]; then
              TAGS="$TAGS,$IMAGE:latest"
            fi
          fi
          echo "Version: $VERSION"
          echo "Main tag: $MAIN_TAG"
          echo "Tags: $TAGS"
          echo "version=$VERSION" >>$GITHUB_OUTPUT
          echo "main-tag=$MAIN_TAG" >>$GITHUB_OUTPUT
          echo "tags=$TAGS" >>$GITHUB_OUTPUT
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          # See https://github.com/docker/build-push-action/issues/654#issuecomment-1285190151
          config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-cache-${{ matrix.distro }}-${{ hashFiles('**/Cargo.lock', 'docker/build-scripts/*') }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-${{ matrix.distro }}-
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (docker.io/mirakc/mirakc)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.${{ matrix.distro }}
          target: mirakc
          platforms: ${{ matrix.platforms }}
          tags: ${{ format(steps.docker-tags.outputs.tags, 'mirakc/mirakc') }}
          cache-from: |
            type=local,src=/tmp/.docker-cache
          cache-to: |
            type=local,dest=/tmp/.docker-cache-new
          push: true
      - name: Build and push (docker.io/mirakc/timeshift-fs)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.${{ matrix.distro }}
          target: mirakc-timeshift-fs
          platforms: ${{ matrix.platforms }}
          tags: ${{ format(steps.docker-tags.outputs.tags, 'mirakc/timeshift-fs') }}
          cache-from: |
            type=local,src=/tmp/.docker-cache-new
          cache-to: |
            type=local,dest=/tmp/.docker-cache-new
          push: true
      - name: Test (docker.io/mirakc/mirakc)
        run: |
          # Enable experimental CLI features in Docker daemon.
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart

          TAG="${{ format(steps.docker-tags.outputs.main-tag, 'mirakc/mirakc') }}"
          for platform in $(echo ${{ matrix.platforms }} | tr ',' ' ')
          do
            echo "Testing $TAG for $platform..."
            docker run --rm --platform=$platform $TAG --version
            docker run --rm --platform=$platform --entrypoint=recdvb $TAG --version
            docker run --rm --platform=$platform --entrypoint=recpt1 $TAG --version
            docker run --rm --platform=$platform --entrypoint=mirakc-arib $TAG --version
            docker run --rm --platform=$platform --entrypoint=mirakc $TAG --version
            docker run --rm --platform=$platform --entrypoint=dvbv5-zap $TAG --version
          done
      - name: Test (docker.io/mirakc/timeshift-fs)
        run: |
          # Enable experimental CLI features in Docker daemon.
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart

          TAG="${{ format(steps.docker-tags.outputs.main-tag, 'mirakc/timeshift-fs') }}"
          for platform in $(echo ${{ matrix.platforms }} | tr ',' ' ')
          do
            echo "Testing $TAG for $platform..."
            docker run --rm --platform=$platform --entrypoint=mirakc-timeshift-fs $TAG --version
          done
      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.docker-cache
          mv /tmp/.docker-cache-new /tmp/.docker-cache
