name: release

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    uses: mirakc/mirakc/.github/workflows/docker.yml@main
    with:
      ref-name: ${{ github.ref_name }}  # tag name
      ref-type: ${{ github.ref_type }}  # tag
    secrets: inherit
