name: update

on:
  workflow_call:
    inputs:
      ref-name:
        required: true
        type: string
    outputs:
      num-commits:
        description: >-
          The number of commits made in this workflow.
        value: ${{ jobs.update.outputs.num-commits }}

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      num-commits: ${{ steps.count.outputs.num-commits }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref-name }}
      - name: git config
        run: |
          # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Update .devcontainer/Dockerfile
        run: |
          ./scripts/update-devcontainer-dockerfile
      - name: Update mirakc-arib
        if: inputs.ref-name == 'main'
        run: |
          ./scripts/update-mirakc-arib
      - name: Push if changed
        run: |
          if git diff --quiet origin/${{ inputs.ref-name }}..HEAD
          then
            echo "No commit to push"
          else
            git push
          fi
      - name: Count commits made within 24 hours
        id: count
        run: |
          NUM_COMMITS=$(git rev-list --count --since '24 hours' ${{ inputs.ref-name }})
          echo "NUM_COMMITS=$NUM_COMMITS"
          echo "num-commits=$NUM_COMMITS" >>$GITHUB_OUTPUT
