name: weekly

on:
  schedule:
    - cron: '19 19 * * 5'  # every Friday

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: raven-actions/bot-details@v1
        id: bot-details
      - uses: actions/checkout@v3
        with:
          # Always checkout the release branch.
          ref: release
          # Fetch all history for all tags and branches so that `git describe`
          # works properly.
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable  # required for scripts/bump-version
      - name: git config
        run: |
          git config user.name "${{ steps.bot-details.outputs.name }}"
          git config user.email "${{ steps.bot-details.outputs.email }}"
      - run: |
          TAG="$(git describe --tags --abbrev=0)"
          if git diff --quiet "$TAG"
          then
            echo "Not changed, skip to create new release"
          else
            ./scripts/release patch
            git push
            git push --tags
          fi
