name: Weekly

on:
  schedule:
    #- cron: '19 19 * * 5'  # 19:19 (UTC), Friday
    - cron: '* * * * *'  # for testing

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # https://github.community/t/push-from-action-even-with-pat-does-not-trigger-action/17622
          persist-credentials: false
          # Fetch all history for all tags and branches so that `git describe` works properly
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: git config
        run: |
          # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: |
          TAG="$(git describe --tags --abbrev=0)"
          if git diff --quiet "$TAG"
          then
            echo "Not changed, skip to create new release"
          else
            sudo apt-get install -y moreutils  # sponge
            ./scripts/release patch
            hub push
            hub push --tags
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
